export const page: string;
export const main: string;
export const form_wrapper: string;
export const avatar: string;
export const field: string;
export const submit: string;
export const logout: string;
export const side: string;
export const left: string;
