export const companions = [
  {
    id: '1',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '2',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '3',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '4',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '5',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '6',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '7',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '8',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '9',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '10',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '11',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '12',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '13',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '14',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '15',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '16',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
  {
    id: '17',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 0,
    date: 'Пт',
    message: 'Очень важное сообщение',
  },
  {
    id: '18',
    name: 'Николай',
    surname: 'Иванов',
    login: 'nik_ivanov',
    unreadMessagesCount: 2,
    date: '07.10',
    message: 'Очень важное сообщение',
  },
];

export default {
  companions,
};
